# Generated by Django 3.0.3 on 2020-02-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='property',
        ),
    ]
