# Generated by Django 3.0.3 on 2020-03-01 17:39

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.Address'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_image_upload_to),
        ),
    ]
