# Generated by Django 3.0.4 on 2020-03-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200302_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
