# Generated by Django 3.0 on 2020-03-15 19:36

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200307_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='document',
            field=models.FileField(upload_to=properties.models.property_docs_upload_to),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.DocumentType'),
            preserve_default=False,
        ),
    ]
