# Generated by Django 3.0 on 2020-03-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200315_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
