# Generated by Django 3.0.6 on 2020-05-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200322_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.Address'),
            preserve_default=False,
        ),
    ]
