# Generated by Django 3.0.7 on 2020-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
