# Generated by Django 3.0.7 on 2020-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
